server:
  port: 80

logging:
    level:
      root: INFO

management:
  endpoints: 
    web:
      exposure:
        include: "*"
    
  endpoint:
    shutdown:
      enabled: true

netty:
  websocket:
    # Websocket服务端口
    port: 1024
    # 绑定的网卡
    ip: 0.0.0.0
    # 消息帧最大体积
    max-frame-size: 10240
    # URI路径
    path: /channel



#依赖包
#mysql-connector-java
#mybatis-plus-boot-starter
# 对应的Bean config： MybatisPlusConfig
# 注意： 使用 brave-instrumentation-mysql8 的时候，
#       需要在url上加入queryInterceptors，exceptionInterceptors，zipkinServiceName(非必填，默认为mysql-dbname)
#===============[datasource]===================================================================================================
spring:
  datasource:
    url:
    username:
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 4
      maximum-pool-size: 64
      #连接超时时间
      connection-timeout: 5000

#===============[orm]===================================================================================================:
mybatis-plus:
  configuration:
    # 日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: io.springboot.netty.**.entity
  type-handlers-package: com.citict.**.typehandler
